# This workflow will use words/words.md to generate a new index.html

name: "Compile index.html from words.md"

on:
  push:
    branches: [ master ]

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - name: Get the current source from master
        uses: actions/checkout@master
      - name: Convert markdown to html
        uses: docker://pandoc/core:2.9 # use a docker image that has pandoc pre-installed
        with:
          args: "--from markdown_strict+footnotes words/words.md -o words/words.html"
      - name: Merge html files
        run: |
          cat index_head.html words/words.html index_tail.html > index.html
      - name: Commit and push changes if files have changed
        uses: stefanzweifel/git-auto-commit-action@v4.1.6
        with:
          commit_message: Compile index.html from Markdown
          commit_user_name: GitHub Action
          commit_user_email: action@github.com
